const Icons = {
    backArrow: require('./icons/backArrow.png'),
    bell: require('./icons/bell.png'),
    search: require('./icons/search.png'),
    graySearch: require('./icons/graySearch.png'),
    speaker: require('./icons/speaker.png'),
    favoritesBT: require('./icons/favoritesBT.png'),
    homeBT: require('./icons/homeBT.png'),
    menuBT: require('./icons/menuBT.png'),
    personBT: require('./icons/personBT.png'),
    noChatsYet: require('./icons/noChatsYet.png'),
    threeDots: require('./icons/threeDots.png'),
    plus: require('./icons/plus.png'),
    send: require('./icons/send.png'),
    eye: require('./icons/eye.png'),
    pin: require('./icons/pin.png'),
    blackSearch: require('./icons/blackSearch.png'),
    delete: require('./icons/delete.png'),
    reply: require('./icons/reply.png'),
    forward: require('./icons/forward.png'),
    copy: require('./icons/copy.png'),
    star: require('./icons/star.png'),
    report: require('./icons/report.png'),
};

export {Icons};
